### PR TITLE
Tiered cables, and removed two Achievements because they were erroring.

### PR DESCRIPTION
**Pull request by qrmcat**
Added cables with tiers 1-3. Removed recipes for all cables except t1 low voltage one, because we will soon be making the cable-maker.

### CODE REVIEW

**Review by PatriikPlays — CHANGES_REQUESTED** [review]
Spaces after entries in the lang files could have been there for spacing after the `:`.

**Comment by qrmcat** [comment]
literally can't add them back for some reason

**Comment by qrmcat** [comment]
Can you approve please?

**Comment by PatriikPlays** [comment]
notepad is a superior *ide*

**Review by PatriikPlays — APPROVED** [review]

**Pull request merged**
